spring.application.name=MCP-server
server.port=9003

spring.ai.mcp.server.name=ntg-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.instructions=This server provides external tools and resources
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false

google.api.key=${GOOGLE_API_KEY:Your Google API key}
google.search.endpoint=https://www.googleapis.com/customsearch/v1
google.search.engine.id=${GOOGLE_SEARCH_ENGINE_ID:Your search engine id}
google.search.sort=date
