spring.application.name=MCP-server
server.port=9003

spring.ai.mcp.server.name=ntg-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.instructions=This server provides external tools and resources
# Turn on STDIO if you want to use desktop host
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=true
spring.ai.mcp.server.capabilities.prompt=true

google.api.key=AIzaSyB2oEbwj8ofcEoR0qz8bYRPvbwQRZ5oe9c
google.search.endpoint=https://www.googleapis.com/customsearch/v1
google.search.engine.id=2536393a412b04d72
google.search.sort=date
