insert into agent (
    name,
	model,
	description,
	temperature,
	max_tokens,
	top_p,
	frequency_penalty,
	presence_penalty,
	active,
	provider,
	settings,
	base_url,
	api_key,
	chat_completions_path,
	embeddings_path,
	embedding_model,
	dimension,
	"version")
values
	 (  'Default agent',
        'gpt-4o',
        'Optional description',
        0.70,
        2048,
        1.00,
        0.00,
        0.00,
        true,
        'Open AI',
        null,
        'https://models.github.ai/inference',
        'Dummy Github API key',
        '/v1/chat/completions',
        '/embeddings',
        'openai/text-embedding-3-small',
        1536,
        0
    );
