ALTER TABLE agent
ADD COLUMN base_url VARCHAR(150) NOT NULL DEFAULT '',
ADD COLUMN api_key VARCHAR(200) NOT NULL DEFAULT '',
ADD COLUMN chat_completions_path VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN embeddings_path VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN embedding_model VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN dimension INTEGER NOT NULL DEFAULT 1536;

